-- AlterTable
ALTER TABLE "messages" ADD COLUMN     "audio_seconds" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "input_tokens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "output_tokens" INTEGER NOT NULL DEFAULT 0;
